language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE colorpicker_test;' -U postgres
  - knex migrate:latest --env=test
notifications: 
  email: false
deploy: 
  provider: heroku

