language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE colorpicker_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: nrQoYoTGeFzYQVNQvZL3luwx3rJKpxOu21/7Zm8MslkC7WEgPbwB552jjMmqmpS0nxiBoTSJ3LInf8zDDC2iLBV4gRGNHgb4jGGKjG1U7Wrz/uhbtEv0h3nF8Ie8fZ4qxfTD+OWgV8jNtTOp9z3sN3d7cKJt4NA7rDOSof/6KgObFcT4eY5oDvR5wXRngH4ArG2OvBrfT2QJOrzINXo85EavEKjbpZUVovF3e56HKoViepZTlhkItHj4mEAfXgirzi9XFX66Z4VuioLIo4XVHi/mLBT0S1z8UhJKdkEeBM+6tKuHRpsC4IUQsVmVD01ShmA0+U5f5zc4V1Ple0yKvbi5El20vFGV2dPReKFbT2NBfOqcW1okhrbxDHloYn9vuFnYHTBcx+vST/WX7LFHgN7M8qLZBcWDC5eRkxa9SzXzwiQPvt+FiZ85vcACdRXWQM5QWpZ+fS/jskYwpVo+eJ05MAEA87IQOop76bRyYsZ2BZQyqUnQG7smjtyQ6AfaIQpad/ktNnLLDkDMXzTqCdROpPyaYWDqksLZZLfXBi5mFKWod6WGc7EAabLT2oHTDFvjQRzZBLbEr2Y2DtpUgP+GosrOXlTT/3JSv/KXy7EewVNjfiORdmzsxFGcKApNdqYrFJY7A6zZ/OrHMNARenKz9/Jz9LOfpwdrQ0u9yRc=
  app: pp-be
  skip_cleanup: true 
  repo: N-Gibson/back-end-palette-picker
